import subprocess
import datetime
import os

def generate_build_info():
    build_date = datetime.datetime.now().isoformat()
    commit = "unknown"
    branch = "unknown"
    is_dirty = False

    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        pass

    try:
        branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"], text=True).strip()
    except Exception:
        pass

    try:
        status = subprocess.check_output(["git", "status", "--porcelain"], text=True).strip()
        is_dirty = len(status) > 0
    except Exception:
        pass

    content = f'''# Auto-generated by build.py. Do not edit manually.
BUILD_DATE = "{build_date}"
BUILD_COMMIT = "{commit}"
BUILD_BRANCH = "{branch}"
IS_DIRTY = {is_dirty}
'''
    target_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config", "build_info.py")
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated build_info.py at {target_path}")

if __name__ == "__main__":
    generate_build_info()
